version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pipoca123
      POSTGRES_DB: decryptdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Mounts the init directory
    # user: root  # Uncomment only if you need to run commands as root

volumes:
  pgdata:
    driver: local
