// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: encrypt.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncryptService_EncryptData_FullMethodName = "/encrypt_service.EncryptService/EncryptData"
)

// EncryptServiceClient is the client API for EncryptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncryptServiceClient interface {
	EncryptData(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
}

type encryptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptServiceClient(cc grpc.ClientConnInterface) EncryptServiceClient {
	return &encryptServiceClient{cc}
}

func (c *encryptServiceClient) EncryptData(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, EncryptService_EncryptData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptServiceServer is the server API for EncryptService service.
// All implementations must embed UnimplementedEncryptServiceServer
// for forward compatibility.
type EncryptServiceServer interface {
	EncryptData(context.Context, *EncryptRequest) (*EncryptResponse, error)
	mustEmbedUnimplementedEncryptServiceServer()
}

// UnimplementedEncryptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncryptServiceServer struct{}

func (UnimplementedEncryptServiceServer) EncryptData(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptData not implemented")
}
func (UnimplementedEncryptServiceServer) mustEmbedUnimplementedEncryptServiceServer() {}
func (UnimplementedEncryptServiceServer) testEmbeddedByValue()                        {}

// UnsafeEncryptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptServiceServer will
// result in compilation errors.
type UnsafeEncryptServiceServer interface {
	mustEmbedUnimplementedEncryptServiceServer()
}

func RegisterEncryptServiceServer(s grpc.ServiceRegistrar, srv EncryptServiceServer) {
	// If the following call pancis, it indicates UnimplementedEncryptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncryptService_ServiceDesc, srv)
}

func _EncryptService_EncryptData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptServiceServer).EncryptData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptService_EncryptData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptServiceServer).EncryptData(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncryptService_ServiceDesc is the grpc.ServiceDesc for EncryptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncryptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encrypt_service.EncryptService",
	HandlerType: (*EncryptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptData",
			Handler:    _EncryptService_EncryptData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encrypt.proto",
}
