// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: decrypt.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecryptService_DecryptData_FullMethodName = "/decrypt_service.DecryptService/DecryptData"
)

// DecryptServiceClient is the client API for DecryptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecryptServiceClient interface {
	DecryptData(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type decryptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecryptServiceClient(cc grpc.ClientConnInterface) DecryptServiceClient {
	return &decryptServiceClient{cc}
}

func (c *decryptServiceClient) DecryptData(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, DecryptService_DecryptData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecryptServiceServer is the server API for DecryptService service.
// All implementations must embed UnimplementedDecryptServiceServer
// for forward compatibility.
type DecryptServiceServer interface {
	DecryptData(context.Context, *DecryptRequest) (*DecryptResponse, error)
	mustEmbedUnimplementedDecryptServiceServer()
}

// UnimplementedDecryptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecryptServiceServer struct{}

func (UnimplementedDecryptServiceServer) DecryptData(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptData not implemented")
}
func (UnimplementedDecryptServiceServer) mustEmbedUnimplementedDecryptServiceServer() {}
func (UnimplementedDecryptServiceServer) testEmbeddedByValue()                        {}

// UnsafeDecryptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecryptServiceServer will
// result in compilation errors.
type UnsafeDecryptServiceServer interface {
	mustEmbedUnimplementedDecryptServiceServer()
}

func RegisterDecryptServiceServer(s grpc.ServiceRegistrar, srv DecryptServiceServer) {
	// If the following call pancis, it indicates UnimplementedDecryptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecryptService_ServiceDesc, srv)
}

func _DecryptService_DecryptData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecryptServiceServer).DecryptData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecryptService_DecryptData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecryptServiceServer).DecryptData(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DecryptService_ServiceDesc is the grpc.ServiceDesc for DecryptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecryptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decrypt_service.DecryptService",
	HandlerType: (*DecryptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecryptData",
			Handler:    _DecryptService_DecryptData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "decrypt.proto",
}
